checks:
    javascript: true
build:
    environment:
        mongodb: true
        node: v7.7.3
    tests:
        override:
            -
                command: 'npm install && npm run test-scrutinizer'
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'clover'
