checks:
    javascript: true
build:
    tests:
        override:
            -
                command: 'npm install && npm run install-client && npm run build-client && npm run test-scrutinizer'
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'clover'
