language: node_js
node_js:
    - "node"
    - "7"
    - "8"

before_script:
    - npm install
    - npm run install-client
    - npm run build-client

script:
    - npm test

after_success:
    - npm run report-codecov
